services:
  app:
    build:
      context: .
    image: fastapi-app
    command: [
      "/opt/.venv/bin/uvicorn",
      "app.app:app",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--reload"
    ]
    ports:
      - "8000:8000"
    volumes:
      - ./app:/opt/app
